@echo off
:: This script was auto-generated by generate-label-script.py
:: It runs a series of commands to print labels.

:: --- Label command for row 1 ---
echo Executing command for row 1...
python label-printer.py --message "Dad's Monster" --border-message "August 12, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 2 ---
echo Executing command for row 2...
python label-printer.py --message "Dad's Monster" --border-message "August 13, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 3 ---
echo Executing command for row 3...
python label-printer.py --message "Dad's Monster" --border-message "August 14, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 4 ---
echo Executing command for row 4...
python label-printer.py --message "Dad's Monster" --border-message "August 15, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 5 ---
echo Executing command for row 5...
python label-printer.py --message "Dad's Monster" --border-message "August 16, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 6 ---
echo Executing command for row 6...
python label-printer.py --message "Dad's Monster" --border-message "August 17, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 7 ---
echo Executing command for row 7...
python label-printer.py --message "Dad's Monster" --border-message "August 18, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 8 ---
echo Executing command for row 8...
python label-printer.py --message "Dad's Monster" --border-message "August 19, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 9 ---
echo Executing command for row 9...
python label-printer.py --message "Dad's Monster" --border-message "August 20, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 10 ---
echo Executing command for row 10...
python label-printer.py --message "Dad's Monster" --border-message "August 21, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 11 ---
echo Executing command for row 11...
python label-printer.py --message "Dad's Monster" --border-message "August 22, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 12 ---
echo Executing command for row 12...
python label-printer.py --message "Dad's Monster" --border-message "August 23, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 13 ---
echo Executing command for row 13...
python label-printer.py --message "Dad's Monster" --border-message "August 24, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 14 ---
echo Executing command for row 14...
python label-printer.py --message "Dad's Monster" --border-message "August 25, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 15 ---
echo Executing command for row 15...
python label-printer.py --message "Dad's Monster" --border-message "August 26, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 16 ---
echo Executing command for row 16...
python label-printer.py --message "Dad's Monster" --border-message "August 27, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 17 ---
echo Executing command for row 17...
python label-printer.py --message "Dad's Monster" --border-message "August 28, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 18 ---
echo Executing command for row 18...
python label-printer.py --message "Dad's Monster" --border-message "August 29, 2025" --side-border "No slurpy slurpy!"

:: --- Label command for row 19 ---
echo Executing command for row 19...
python label-printer.py --message "Dad's Monster" --border-message "August 30, 2025" --side-border "No slurpy slurpy!"


echo All label commands executed successfully.
pause
